/**
 * OnfonMediaSMSGatewayLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';


const Configuration = {
    // The base Uri for API calls
    BASEURI: 'https://api.onfonmedia.co.ke/v1/sms',

    // Network Layer Access Key
    accessKey: 'ACCESS_KEY',

    // Used for authentication purpose and pass this parameter in URL encoded format.
    apiKey: 'API_KEY',

    // Used for authentication purpose and pass this parameter in URL encoded format.
    clientId: 'CLIENT_ID',

};

module.exports = Configuration;
